name: CI

on:
  push:
    # The docker branch tracks master, so it doesn't need testing separately
    branches-ignore:
      docker
  pull_request:

defaults:
  run:
    shell: bash

jobs:
  # This workflow contains a single job called "check"
  check:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        R: [ '3.6.2', '4.2.3', 'release' ]
    
    steps:
    - name: Check out code
      uses: actions/checkout@v3
      with:
        submodules: true
    
    - name: Install and set up R
      uses: r-lib/actions/setup-r@v2
      with:
        r-version: ${{ matrix.R }}
    
    - name: Cache dependencies
      id: cache-deps
      uses: actions/cache@v3
      with:
        path: lib/R
        key: ${{ runner.os }}-deps-${{ matrix.R }}-${{ hashFiles('lib/*/DESCRIPTION') }}
    
    - if: ${{ steps.cache-deps.outputs.cache-hit != 'true' }}
      name: Install dependencies
      run: make install-libs
    
    - name: Install main packages
      run: make install-main
    
    - name: Run tests
      run: make deeptest
    
    - name: Generate debug test output
      if: failure()
      run: make dtest
