name: CI

on:
  push:
    # The docker branch tracks master, so it doesn't need testing separately
    branches-ignore:
      docker
  pull_request:

defaults:
  run:
    shell: bash

jobs:
  # This workflow contains a single job called "check"
  check:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        R: [ '3.5.0', '4.0.0', 'release' ]
    
    steps:
    - name: Check out code
      uses: actions/checkout@v4
      with:
        submodules: true
    
    - name: Install and set up R
      uses: r-lib/actions/setup-r@v2
      with:
        r-version: ${{ matrix.R }}
    
    # igraph depends on glpk in the 2.0.x series, so this is required for deep testing
    - name: Install upstream system dependencies
      run: sudo apt-get install -y libglpk-dev
    
    - name: Cache dependencies
      id: cache-deps
      uses: actions/cache@v3
      with:
        path: lib/R
        key: ${{ runner.os }}-deps-${{ matrix.R }}-${{ hashFiles('lib/*/DESCRIPTION') }}
    
    - name: Install dependencies
      if: ${{ steps.cache-deps.outputs.cache-hit != 'true' }}
      run: make install-libs
    
    - name: Install main packages
      run: make install-main
    
    - name: Run tests
      run: make deeptest
