name: Debug

on:
  push:
    branches:
    - debug

jobs:
  # Run tests with debugging output
  test-debug:
    runs-on: ubuntu-latest
    
    strategy:
      fail-fast: false
    
    steps:
    - name: Check out code
      uses: actions/checkout@v4
      with:
        submodules: true
    
    - name: Install and set up R
      uses: r-lib/actions/setup-r@v2
    
    - name: Install packages
      run: make install
    
    - name: Run tests in debug mode
      run: make dtest
